ACSLXTREME_SETUP = C:\acslX\setup.in
AXLITEPATH = C:\acslX
MODEL_NAME = molly2
MODEL_DIR = I:\Simon\Projects\Molly_Translation\csl2cpp\molly
TARGET_FULL = molly2.dll
MODEL_RRR_FULL = molly2.rrr
include C:\acslX\makedefs
